### ISSUE TITLE
Selected image is reset on form error

### ISSUE THREAD

**Issue by zudheer** [dima-kov/django-croppie#2]
When a form has an error. ie form is invalid, the image selected is reset and user has to re upload the image,

**Comment by dima-kov** [comment]
This is not `croppie` issue, is is normal browser's behaviour. Read more https://stackoverflow.com/a/36344934/4640928

**Comment by dima-kov** [comment]
Closing

**Comment by zudheer** [comment]
I am saying about django form invalid. The file is still available on form.invalid. 
Atleast is it possible to set a initial image file manually? i,e inside django view set_initial() method

**Comment by dima-kov** [comment]
Have you tried to accomplish this behaviour on the usual django form without croppie?

**Comment by zudheer** [comment]
Yes.

**Comment by dima-kov** [comment]
Could I see your code? Simply, I can't exactly understand what do you need to achive in the result

**Comment by dima-kov** [comment]
Closed
