### ISSUE TITLE
Template croppie/widget.html didn't find 

### ISSUE THREAD

**Issue by alexfaraday** [dima-kov/django-croppie#20]
I have a exception about  django can't find a template - croppie/widget.html

1 | {% spaceless %**}{% for widget in widget.subwidgets %}**{% include widget.template_name %}****{% endfor %}{% endspaceless %}

**Comment by dima-kov** [comment]
Probable, you have not added `croppie` to `INSTALLED_APPS`

**Comment by dima-kov** [comment]
Closing now
