### ISSUE TITLE
what about default image?

### ISSUE THREAD

**Issue by ParsaFakhar** [dima-kov/django-croppie#3]
image = models.ImageField(default='default.jpg', upload_to='profile_pics')

as you can see i need to set  a default image and  the location how to do this with:

photo = CroppieField()

**Comment by dima-kov** [comment]
What do you mean?

`image = models.ImageField(default='default.jpg', upload_to='profile_pics')` - is used in models. But `photo = CroppieField()` is used in forms.

**Comment by dima-kov** [comment]
Closed due to date
