### ISSUE TITLE
mostrar imágenes en plantillas

### ISSUE THREAD

**Issue by jonbravo117** [dima-kov/django-croppie#9]
cómo se pueden mostrar la imagenes en las plantillas en forma de circulo

**Comment by dima-kov** [comment]
Could you, please, explain more? And it would be great to communicate in English, as well, it is hard for me to understand and reply in Espanol.

**Comment by malviyayash18** [comment]
Hi ! i am using croppie and its working fine. I was trying to add some functionality like clicking on a button gives me the cropped image [working fine] but i also wanted to add a button which takes be back to crop the same uploaded image. is there a way to render croppie again without actually refreshing the page.
ThankYou. ;)

**Comment by yash-malviya** [comment]
> cómo se pueden mostrar la imagenes en las plantillas en forma de circulo


You can change the view to circle by making changes to your viewport to something like this` viewport: {width: 250, height: 250, type: 'circle'}`

**Comment by dima-kov** [comment]
@jonbravo117, seems like an issue is resolved. Close
